### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by combat007** [plusonecoin/plusonecoin#4]
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      plusonecoind-plusonecoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp: In function ‘bool InitHTTPServer()’:
httpserver.cpp:405:27: error: ‘opal_libevent2021_evthread_use_pthreads’ was not declared in this scope
     evthread_use_pthreads();
                           ^
Makefile:5918: recipe for target 'libbitcoin_server_a-httpserver.o' failed
make[2]: *** [libbitcoin_server_a-httpserver.o] Error 1
make[2]: Leaving directory '/windows/plusonecoin/src'
Makefile:9487: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/windows/plusonecoin/src'
Makefile:682: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I am using gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
libevent-pthreads-2.0-5,  libevent-2.0-5

**Comment by ackerman2718** [comment]
I build under ubuntu fine.  Could you cut and paste the output of configure?

**Comment by combat007** [comment]
thanks I resolved the problem, I reinstalled it on a new virtual machine
with all dependencies. It compiled and is working good.

I ll close it on github.

Best Regards
